name: Build and Run OpenGL Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc freeglut3-dev xvfb

    - name: Set up virtual display
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 3  # Wait for Xvfb to start
        export DISPLAY=:99

    - name: Build Finalcode.c
      run: |
        export DISPLAY=:99
        gcc Finalcode.c -lGL -lGLU -lglut -lm -o Finalcode
        chmod +x Finalcode  # Ensure it's executable

    - name: Run Finalcode
      run: |
        export DISPLAY=:99
        ./Finalcode
