name: Build C Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y gcc

    - name: Install OpenGL
      run: sudo apt install freeglut3-dev

    - name: Build Finalcode.c
      run: gcc Finalcode.c -lGL -lGLU -lglut -lm -o Finalcode

    - name: Run Finalcode
      run: ./Finalcode
