name: Build and Run OpenGL Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc freeglut3-dev xvfb

    - name: Set up virtual display
      run: |
        echo "Starting Xvfb..."
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 5  # Wait for Xvfb to initialize
        export DISPLAY=:99
        echo "Xvfb started on DISPLAY=:99"

    - name: Build Finalcode.c
      run: |
        echo "Building Finalcode.c..."
        gcc Finalcode.c -lGL -lGLU -lglut -lm -o Finalcode
        chmod +x Finalcode
        echo "Build completed"

    - name: Run Finalcode
      run: |
        export DISPLAY=:99
        echo "Running Finalcode..."
        timeout 30s ./Finalcode  # Limits execution to 30 seconds to avoid hanging
        echo "Run completed"
